### ISSUE TITLE
Incorrect Dependency versions and lockfiles

### ISSUE THREAD

**Issue by anantoghosh** [mhjadav/gatsby-starter-bootstrap-cv#1]
`gatsby-starter-bootstrap-cv` is using v1 plugins for
```
"gatsby-plugin-google-analytics": "^1.0.31",
"gatsby-plugin-manifest": "^1.0.27",
"gatsby-plugin-offline": "^1.0.18",
```
These need to be v2 plugins for Gatsby 2. Either specify a v2 range or `next` tag.

<hr />
  
This project has both `package-lock.json` and `yarn.lock` files. But the yarn lockfile is out of date and will install incorrect dependencies. Consider using only one package manager and only a single lockfile.

**Comment by mhjadav** [comment]
@anantoghosh thanks for pointing it out

**Comment by mhjadav** [comment]
I updated the package.json file and closing this issue.
@anantoghosh if you feel if I can improve over something else then let know.

Thanks 😄
